call msdev Shark_Libs_Release.dsw /MAKE "Array - Win32 Release" > make_libs_release.log
call msdev Shark_Libs_Release.dsw /MAKE "EALib - Win32 Release" >> make_libs_release.log
call msdev Shark_Libs_Release.dsw /MAKE "LinAlg - Win32 Release" >> make_libs_release.log
call msdev Shark_Libs_Release.dsw /MAKE "Metric - Win32 Release" >> make_libs_release.log
call msdev Shark_Libs_Release.dsw /MAKE "Mixture - Win32 Release" >> make_libs_release.log
call msdev Shark_Libs_Release.dsw /MAKE "RandomDistr - Win32 Release" >> make_libs_release.log
call msdev Shark_Libs_Release.dsw /MAKE "ReClaM - Win32 Release" >> make_libs_release.log
call msdev Shark_Libs_Release.dsw /MAKE "Rng - Win32 Release" >> make_libs_release.log
call msdev Shark_Libs_Release.dsw /MAKE "SimAnn - Win32 Release" >> make_libs_release.log
call msdev Shark_Libs_Release.dsw /MAKE "TimeSeries - Win32 Release" >> make_libs_release.log