call msdev Shark_All_Debug.dsw /MAKE "Array - Win32 Debug" > make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "meanvar - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "EALib - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "ackleyES - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "countingOnes - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "integerES - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "sphereGA - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "sphereOstermeier - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "steadyState - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "LinAlg - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "bfgs2_test - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "bfgs_test - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "cblnsrch - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "covar_corrcoef_test - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "detsymm_test - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "dlinmin_test - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "eigenerr_test - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "eigensort_test - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "eigensymmJacobi2_test - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "eigensymmJacobi_test - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "eigensymm_test - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "fft_test - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "g_inverse_matrix - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "linalg_simple_test - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "linearClassifier_test - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "linearRegression_test - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "linmin_test - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "lnsrch_test - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "pca_test - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "rank_decomp_test - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "rank_test - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "svd_test - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "svdrank_test - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "svdsort_test - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "Metric - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "metric_test - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "Mixture - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "mg_example - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "rbfn_example - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "RandomDistr - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "ReClaM - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "simpleFFNet - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "simpleRBFNet - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "simpleRNNet - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "Rng - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "RngTest - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "RngTest2 - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "RngTestSimple - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "SimAnn - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "testmain - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "TimeSeries - Win32 Debug" >> make_all_debug.log
call msdev Shark_All_Debug.dsw /MAKE "embeddingTest - Win32 Debug" >> make_all_debug.log

